enum Magic {
	no,
	// Alteration
	candlelight,
	detectdead,
	detectlife,
	dragonhide,
	ebonyflesh,
	equilibrium,
	magelight,
	massparalysis,
	oakflesh,
	paralyze,
	ironflesh,
	stoneflesh,
	waterwalking,
	// Conjouration
	banishdaedra,
	boundsword,
	boundbattleaxe,
	boundbow,
	commanddaedra,
	conjourashguardian,
	conjourdremora,
	conjourfamiliar,
	conjourflamingfamiliar,
	conjourflameatronach,
	conjourfrostatronach,
	conjourstormatronach,
	deadthrall,
	dreadzombie,
	expertdaedra,
	flamethrall,
	frostthrall,
	raisezombie,
	reanimatecorpse,
	revenant,
	soultrap,
	stormthrall,
	// Destruction
	blizzard,
	chainlightning,
	firebolt,
	firerune,
	firestorm,
	fireball,
	flamecloak,
	flames,
	frostbite,
	frostcloak,
	frostrune,
	icespike,
	icyspear,
	incinerate,
	lightningbolt,
	lightningcloak,
	lightningrune,
	lightningstorm,
	sparks,
	thunderbolt,
	wallofflames,
	walloffrost,
	wallofstorms,
	// Illusion
	calltoarms,
	calm,
	clairvoyance,
	courage,
	fear,
	frenzy,
	fury,
	harmony,
	hysteria,
	invisibility,
	mayhem,
	muffle,
	pacify,
	rally,
	rout,
	// Restoration
	baneoftheundead,
	circleofprotection,
	closewounds,
	fasthealing,
	grandhealing,
	greaterward,
	guardiancircle,
	healing,
	healinghands,
	healother,
	lesserward,
	repelundead,
	steadfastward,
	turngreaterundead,
	turnlesserundead,
	turnundead,
}

all_magic=array_create(Magic.turnundead, noone);

// Alteration
all_magic[Magic.candlelight]=newMagic("Candlelight", MagicClasses.alteration, MagicLevels.novice, 44, null, mo_candlelight, MagicTargets.user, "Creates hoverling light that lasts 60 seconds.");
all_magic[Magic.magelight]=newMagic("Magelight", MagicClasses.alteration, MagicLevels.apprentice, 87, null, mo_magelight, MagicTargets.user, "Throw a ball of light that sicks where it lands. Lasts 60 seconds.");
all_magic[Magic.oakflesh]=newMagic("Oakflesh", MagicClasses.alteration, MagicLevels.novice, 44, null, null, MagicTargets.user, "Improves the caster's armor rating by 40 points for 60 seconds.");
all_magic[Magic.waterwalking]=newMagic("Water Walking", MagicClasses.alteration, MagicLevels.adept, 340, null, mo_waterwalking, MagicTargets.user, "Walk on water for 60 seconds.");

// Destruction
all_magic[Magic.flames]=newMagic("Flames", MagicClasses.destruction, MagicLevels.novice, 50, null, mo_fire, MagicTargets.single, "Shoot flames from your fingertips. Targets on fire take extra damage.", MagicFlags.fire);
all_magic[Magic.frostbite]=newMagic("Frostbite", MagicClasses.destruction, MagicLevels.novice, 47, null, mo_ice, MagicTargets.single, "A blast of cold air..", MagicFlags.ice);
all_magic[Magic.sparks]=newMagic("Sparks", MagicClasses.destruction, MagicLevels.novice, 46, null, mo_spark, MagicTargets.single, "Create a bolt of lightning that does 10 shock damage to health and 5 to magikca per second.", MagicFlags.shock);