name="Magic";
description="A generic magic spell template.";
school=MagicClasses.alteration;
level=MagicLevels.novice;
flag=MagicFlags.no;
cost=10;
use_script_battle=null;
use_script_overworld=null;
target=MagicTargets.single;